version: '3.8'
services:
    form.postgresql:
        container_name: "${APP_CONTAINER_PREFIX}_postgresql"
        image: postgres:13.7
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - postgresql_data:/var/lib/postgresql/data
            - ./docker-files:/tmp/dump
        ports:
            - "5432:5432"

    form.php:
        container_name: "${APP_CONTAINER_PREFIX}_php"
        build: ./docker/php
        working_dir: ${WORKING_DIR}
        environment:
            PHP_XDEBUG_MODE: ${PHP_XDEBUG_MODE}
            PHP_XDEBUG_CLIENT_PORT: ${PHP_XDEBUG_CLIENT_PORT}
            PHP_XDEBUG_CLIENT_HOST: ${PHP_XDEBUG_CLIENT_HOST}
            DATABASE_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@form.postgresql:5432/${DB_DATABASE}
        volumes:
            - ./:${WORKING_DIR}
        links:
            - form.postgresql
            - form.memcached
            - form.redis

    form.nginx:
        container_name: "${APP_CONTAINER_PREFIX}_nginx"
        image: nginx
        links:
            - form.php
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ./:${WORKING_DIR}
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    form.memcached:
        container_name: "${APP_CONTAINER_PREFIX}_memcached"
        image: memcached:latest

    form.redis:
        container_name: "${APP_CONTAINER_PREFIX}_redis"
        image: redis:latest
        ports:
            - "${REDIS_PORT}:6379"

    form.supervisor:
        container_name: "${APP_CONTAINER_PREFIX}_supervisor"
        build: ./docker/supervisor
        working_dir: ${WORKING_DIR}
        environment:
            DATABASE_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@form.postgresql:5432/${DB_DATABASE}
        volumes:
            - ./:${WORKING_DIR}
        links:
            - form.postgresql
            - form.redis

volumes:
    postgresql_data:
